version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:20.10.3-git
    resource_class: small
    steps:
      - checkout
      - run:
          name: Remove host key checking
          command: |
            mkdir -m 700 -p ~/.ssh/
            echo $'Host *\n    StrictHostKeyChecking no' > ~/.ssh/config
            chmod 644 ~/.ssh/config
      - run:
          name: Run build
          command: |
            docker --debug -H=ssh://${USER}@${HOST} build --rm -t elasticsearch:7.9-alpine ./7.9/
      # - run:
      #     name: Run elasticsearch
      #     command: |
      #       set -x
      #       docker run -d --name es -p 9200:9200 -e cluster.name=testcluster -e discovery.type=single-node app; sleep 20
      #       docker logs es
      # - run:
      #     name: Run test
      #     command: |
      #       set -x
      #       docker run --rm --network container:es blacktop/httpie GET http://localhost:9200
